### ISSUE TITLE
Can't read data from kits without upper marker

### ISSUE THREAD

**Issue by adityabandla** [jwfoley/bioanalyzeR#1]
Thanks for the scripts, I am not sure if you are still actively developing it. When I tried to read in the PNG image of the gel photo, I get the following error

which.x.upper.marker == which.x.lower.marker are not all TRUE

Appreciate if you could guide me with this

**Comment by jwfoley** [comment]
Thanks for your interest. I've been developing this project on and off, and it's not entirely in a working state, but now that I know someone else is interested I'll try to return to it as time permits.

Can you upload an example PNG that causes this error?

**Comment by adityabandla** [comment]
Thanks for the quick reply. The PNG which I tried to import is below
![2018-09-26-03-metag_dna_batch 9_gel photo](https://user-images.githubusercontent.com/17331245/46556736-257bc080-c91a-11e8-9995-f0fdde8071d2.png)

**Comment by jwfoley** [comment]
It looks like this is from the genomic DNA kit, and unfortunately the current implementation depends on finding the lower and upper marker bands but the gDNA kit has no upper marker (neither do the RNA kits). That part of the approach will need some fundamental changes to accommodate these kits. I'll update this thread when that's solved.

**Comment by adityabandla** [comment]
Yes, indeed it is from the gDNA kit. Thank you again for the quick response. I will await for further updates

**Comment by jwfoley** [comment]
Marking this as resolved since it seems to work in my tests.
