### ISSUE TITLE
Error in rbind when using read.electrophoresis

### ISSUE THREAD

**Issue by upu891** [jwfoley/bioanalyzeR#12]
Thanks for creating this package.  It looks to be useful.  I ran into an error when using read.electrophoresis though.  I am trying to read an xml file that was exported using Expert 2100 (Bioanalyzer data; D 1000;  8 samples) as described, but I get an error.

[test2.xml.gz](https://github.com/jwfoley/bioanalyzeR/files/4760666/test2.xml.gz)

> 
> Error in rbind(deparse.level, ...) : 
>   numbers of columns of arguments do not match

version

> platform       x86_64-pc-linux-gnu         
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          4                           
> minor          0.0                         
> year           2020                        
> month          04                          
> day            24                          
> svn rev        78286                       
> language       R                           
> version.string R version 4.0.0 (2020-04-24)
> nickname       Arbor Day                   

Thank you for your time.

**Comment by jwfoley** [comment]
Release 0.3.2 contains this patch.
