### ISSUE TITLE
Not able to run BioanalyzeR in new R version 4.0.2

### ISSUE THREAD

**Issue by GiuliaZ538** [jwfoley/bioanalyzeR#13]
Hi jwfoley, I think that this package is very useful for overlaying Bioanalyzer profiles, and I would like to use it for my BA results.
I am a pretty new user of R so maybe my question is an easy one. 
When installing the package an error occurs:

> install.packages("https://github.com/jwfoley/bioanalyzeR/releases/download/v0.4.3/bioanalyzeR_0.4.3.tar.gz")
Warning in install.packages :
  package ‘https://github.com/jwfoley/bioanalyzeR/releases/download/v0.4.3/bioanalyzeR_0.4.3.tar.gz’ is not available (for R version 4.0.2)

I have downloaded also the version 3.6.3 but the same warning occurred (MAC versions). 
How can I run the package?
Which is the R version that allows me to run the package?
Are there any tricks to make it work?

Thank you for the help,
Best regards,
Giulia

**Comment by jwfoley** [comment]
I'm not sure what's happening here; both versions of R are able to install the package from that URL on my computer. It seems like your R is searching the repositories for a package with that URL as the name rather than simply downloading from the URL, which is not the documented behavior of `install.packages`. 

What if you try

    install.packages("https://github.com/jwfoley/bioanalyzeR/releases/download/v0.4.3/bioanalyzeR_0.4.3.tar.gz", repos = NULL)

? Or if that doesn't work, manually download the file from that URL, and then

    install.packages("PATH_WHERE_YOU_DOWNLOADED_IT/bioanalyzeR_0.4.3.tar.gz", repos = NULL)

**Comment by GiuliaZ538** [comment]
Hi, thank you for the suggestions, I tried both methods, this is the warning message:
ERROR: dependencies ‘XML’, ‘png’ are not available for package ‘bioanalyzeR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/bioanalyzeR’
Warning message:
In install.packages("~/Documents/R trials/bioanalyzeR_0.4.3.tar.gz",  :
  installation of package ‘/Users/R trials/bioanalyzeR_0.4.3.tar.gz’ had non-zero exit status

Not clear what happened here. Maybe some settings of my Mac.
Best,
Giulia

**Comment by jwfoley** [comment]
You need to install the missing dependencies:

    install.packages("XML")
    install.packages("png")

**Comment by GiuliaZ538** [comment]
Thank you! I managed to install the package! Now it's working! Thank you very much for your help!
