### ISSUE TITLE
Issue with "non.marker.areas" when reading XML file?

### ISSUE THREAD

**Issue by dannyconrad** [jwfoley/bioanalyzeR#19]
Hi, just stumbled across this package and very excited to use it. I have two XML files generated from two BA chips I ran on the same day with similar samples. One file reads no problem, the other throws this error:

`Error in electrophoresis$peaks$concentration[non.marker.peaks]/non.marker.areas :    non-numeric argument to binary operator`

I admittedly haven't dug into this too much yet but I'm wondering if you might be able to offer any advice on what might be wrong here?

**Comment by jwfoley** [comment]
Can you upload the XML file that doesn't work? Feel free to anonymize the sample names if necessary.

**Comment by dannyconrad** [comment]
[DC_210419_2_HighSensitivityDNAAssay_DE72905128_2021-04-19_15-56-12.xml.zip](https://github.com/jwfoley/bioanalyzeR/files/6360617/DC_210419_2_HighSensitivityDNAAssay_DE72905128_2021-04-19_15-56-12.xml.zip)

Thank you!

**Comment by jwfoley** [comment]
Can you `install.packages("bioanalyzeR_0.7.1-test.tar.gz")` with this patch and see if that resolves the problem?

[bioanalyzeR_0.7.1-test.tar.gz](https://github.com/jwfoley/bioanalyzeR/files/6361724/bioanalyzeR_0.7.1-test.tar.gz)

**Comment by dannyconrad** [comment]
It worked :) Thank you so much for the quick response!

**Comment by jwfoley** [comment]
Sorry for the bug. Please reinstall the latest version the usual way to ensure reliability.

**Comment by dannyconrad** [comment]
No worries at all! Posting here because its the same sample and so might be related, but the "concentration" variable turns up empty

![image](https://user-images.githubusercontent.com/22381421/115803060-f5d81b00-a394-11eb-8a91-f4ea2476d770.png)


I did reinstall the new 7.1 version as you said.

**Comment by jwfoley** [comment]
Oops. Does this version fix it?

[bioanalyzeR_0.7.1-test2.tar.gz](https://github.com/jwfoley/bioanalyzeR/files/6362112/bioanalyzeR_0.7.1-test2.tar.gz)

**Comment by dannyconrad** [comment]
Yes it does! Much appreciated
