### ISSUE TITLE
Incorrect use of all.equal in read.tapestation.xml

### ISSUE THREAD

**Issue by paulbarber** [jwfoley/bioanalyzeR#24]
Hi, 
Incorrect use of all.equal in read.tapestation.xml causes fatal error when reading some xml files.

The offending line near the end of the function is: 
`else if (all.equal(as.character(result$samples$reagent.id[result$samples$well.number %in% ladder.wells]), levels(result$samples$reagent.id))) {
`

The error is:
```
Error in if (all.equal(as.character(result$samples$reagent.id[result$samples$well.number %in%  : 
  argument is not interpretable as logical
```

Help for all.equals says: 
`Do not use all.equal directly in if expressions—either use isTRUE(all.equal(....)) or identical if appropriate.`

I cannot offer a solution as I cannot obviously see what the behaviour should be. I hope you can fix it soon.
Thank you!

**Comment by jwfoley** [comment]
Thanks for catching this. I remember being confused by `all.equal` and there's a good chance it's wrong there.

Can you upload an XML that gets this error? You can anonymize the samples if necessary.

**Comment by paulbarber** [comment]
Ok, here is the xml and csv.
I try and import that data with this command:
d <- read.tapestation("2022-04-14 - 15-13-24-gDNA.xml", "2022-04-14 - 15-13-24-gDNA.csv", gel.image.file = NULL, method = "hyman")
[2022-04-14 - 15-13-24-gDNA.zip](https://github.com/jwfoley/bioanalyzeR/files/8514537/2022-04-14.-.15-13-24-gDNA.zip)

**Comment by jwfoley** [comment]
It looks like the problem was actually the "Ladder sizing changed" message in your sample observations, which I hadn't encountered before and caused a problem with ladder detection. Can you confirm that this patch fixes the problem? 
[bioanalyzeR_test.tar.gz](https://github.com/jwfoley/bioanalyzeR/files/8516888/bioanalyzeR_test.tar.gz)

    > install.packages("bioanalyzeR_test.tar.gz")

**Comment by paulbarber** [comment]
Yes, our file loads with that patched version. Thank you.

**Comment by jwfoley** [comment]
This patch is included in the [latest release](https://github.com/jwfoley/bioanalyzeR/releases/tag/v0.9.2). Please reinstall that version for best support. Thanks for reporting this problem.
