### ISSUE TITLE
Reasoning for differential.scale

### ISSUE THREAD

**Issue by asn32** [jwfoley/bioanalyzeR#25]
Hi, fantastic package!! 

I had a question about the differential.scale function applied to the y variable when plotting - would you mind explaining why that scaling is necessary? Thanks!

**Comment by jwfoley** [comment]
The goal of these rescaled mass and molarity graphs is that the visible area under the curve is directly proportional to the total mass or molarity in that region, which is the intuitive way of reading them. So the simple mathematical answer is that the units of *y* on the graph have to be molarity per length, *M*/*L*, if *x* is just in units of length *L*, in order for the units of ∫*ydx* to come out as *M*.

The technical reason is that the data points actually recorded on the instrument, and stored in our data frames, are spaced out at regular distances in pixels (TapeStation) or regular time intervals when liquid is passing by the sensors (all other Agilent systems). The correspondence between migration distance/time and molecule length is nonlinear. So if we left the data along those differentials, the area under the curve when we graph vs. molecule length wouldn't be proportional to total mass/molarity as required. Therefore the data points have to be rescaled from the measurement variable to the graphing variable.

A more complex wrinkle is that, except on the TapeStation, faster-migrating molecules also spend less time in front of the fixed detector during the detection interval, so shorter (faster-migrating) molecules will give less fluorescence signal than longer (slower-migrating) molecules of the same total mass even after you account for the fact that they're longer and have more slots for the fluorescent probe to bind. The rescaling also takes that effect into account.

Sorry for the slow reply but thanks for your interest. Does that answer your question? Do you need a new feature to do this a different way?

**Comment by asn32** [comment]
Hi, thanks for your response! Your explanation makes a lot of sense - I've been using your package to estimate the molar concentration of peaks and the average fragment size more accurately, and was curious why plotting molarity vs. length appeared different than the plot produced by BioanalyzeR.

The main feature that would be great to have in addition to the tools you built would be a way to extend the fragment size estimation / molarity concentration past the upper molecular weight ladder. Have you had any success with doing so? thanks!

**Comment by jwfoley** [comment]
OK, I wrote a patch with an undocumented feature to let you say `extrapolate = TRUE` when you read your input data and then all non-negative length estimates are included, so you can view them at your own risk. How does that look?

[bioanalyzeR_extrapolation_test.tar.gz](https://github.com/jwfoley/bioanalyzeR/files/8773217/bioanalyzeR_extrapolation_test.tar.gz)

**Comment by jwfoley** [comment]
> We've just run a test using the ladder from the Bioanalyzer 12K kit that goes up to 17kb, and interestingly that 17kb marker peak runs at around 13kb on the HS chip, where that size was determined by agilent's software (which confirms their extrapolation is pretty inaccurate as well). 

I don't know precisely but I do think this is starting to get into the range where electrophoresis becomes inherently inaccurate without a pulsed field, and certainly I wouldn't expect anything to work well outside the supported range of the kit (the polymer concentration is set for the target size range). If you want this to work you're better off using a TapeStation Genomic DNA kit or a Fragment Analyzer Large Fragment or Genomic DNA kit, or ideally the Femto Pulse system if you can find one.

**Comment by asn32** [comment]
ok awesome - thanks for sharing the patch & your thoughts. I'll let you know how it goes on our end!

**Comment by jwfoley** [comment]
I included this patch in the new [release v0.10.0](https://github.com/jwfoley/bioanalyzeR/releases/tag/v0.10.0) so I'll assume that solves your problem and close this issue. You might also be interested in the new [wrapper function for plotting raw data](https://stanford.edu/~jwfoley/bioanalyzeR.html#raw-data-plots) to get around the mobility calibration altogether, if you just want a qualitative glance at the data outside the bounds.
