### ISSUE TITLE
License

### ISSUE THREAD

**Issue by edjoha** [jwfoley/bioanalyzeR#30]
Hi, 

very nice and useful package! It helped me a lot :)

Just want to raise awareness, that it doesn't seem to have a license, yet. From my understanding, secondary use is not proper legalised without. Please survey the following website by GitHub : https://choosealicense.com/no-permission/

Cheers,

**Comment by jwfoley** [comment]
Thanks for the reminder; this is long overdue. Will add a license in the next release.
