### ISSUE TITLE
could not find function in read.electrophoresis

### ISSUE THREAD

**Issue by ShellySquare** [jwfoley/bioanalyzeR#33]
Hi, I downloaded bioanalyzeR and trying to work through the examples on using the demo data. But I'm not able to use the read.electrophoresis function. The example code is `dna1000 <- read.electrophoresis(system.file(
  "extdata",
  "bioanalyzer",
  "Demo DNA 1000 Series II.xml.gz",
  package = "bioanalyzeR"
))
dna1000$assay.info` and the error that I got is `Error in read.electrophoresis(system.file("extdata", "bioanalyzer", "Demo DNA 1000 Series II.xml.gz",  : 
  could not find function "read.electrophoresis"` 
Help would be appreciated, thank you!

**Comment by jwfoley** [comment]
Sorry to hear it's not working. Can you confirm that you

1. [installed the package on your computer per the README without errors](https://github.com/jwfoley/bioanalyzeR/blob/master/README.md)
2. ran the command `library(bioanalyzeR)` or equivalent at the beginning of your R session to load the package

?

**Comment by ShellySquare** [comment]
that worked, thank you so much! :)

**Comment by ShellySquare** [comment]
That worked, thank you so much!

Best,
Shelly
