### ISSUE TITLE
Can't read TS image file

### ISSUE THREAD

**Issue by drkvnssn** [jwfoley/bioanalyzeR#4]
Unclear how to export the TapeStation png file. 
* should there be 1 highlighted lane or 2?
* with one highlighted: 'Error: length(which.well.is.ladder) == 1 is not TRUE'
* with 'read.tapestation.gel.image()', fluorescence of gel.lane 1 == 0

**Comment by jwfoley** [comment]
Could you please upload your PNG and XML so I can investigate this? You can anonymize the samples and re-export them if privacy is a concern.

**Comment by jwfoley** [comment]
closed due to lack of response
